"""Maia SDK - the collaboration and observability layer for AI agents.

One import, everything you need.

Quick start:

    from maia_sdk import ACPClient, Theatre, TeamChat, create_computer_use_client, message
"""

__version__ = "0.1.0"

from maia_acp import (
    ACPEvent,
    ACPMessage,
    ACPHandoff,
    ACPReview,
    ACPArtifact,
    ACPActivity,
    ACPCapabilities,
    HandoffTask,
    ReviewIssue,
    AgentPersonality,
    AgentSkill,
    ToolActivity,
    BrowserActivity,
    ProgressInfo,
    CostInfo,
    envelope,
    message,
    handoff,
    review,
    artifact,
    activity,
    capabilities,
    ACPClient,
    parse_sse_line,
    stream_events,
    connect_sse,
)
from maia_computer_use import (
    ComputerUseClient,
    ComputerUseClientConfig,
    ComputerUseActiveModelResponse,
    ComputerUsePolicyResponse,
    ComputerUseSessionListRecord,
    ComputerUseSessionRecord,
    ComputerUseSLOSummaryResponse,
    ComputerUseStreamEvent,
    NavigateComputerUseSessionResponse,
    StartComputerUseSessionInput,
    StartComputerUseSessionResponse,
    StreamComputerUseSessionOptions,
    cancel_computer_use_session,
    create_computer_use_client,
    get_computer_use_active_model,
    get_computer_use_policy,
    get_computer_use_session,
    get_computer_use_slo_summary,
    list_computer_use_sessions,
    navigate_computer_use_session,
    start_computer_use_session,
    stream_computer_use_session,
)
from maia_teamchat import TeamChat
from maia_theatre import Theatre

__all__ = [
    "ACPEvent",
    "ACPMessage",
    "ACPHandoff",
    "ACPReview",
    "ACPArtifact",
    "ACPActivity",
    "ACPCapabilities",
    "HandoffTask",
    "ReviewIssue",
    "AgentPersonality",
    "AgentSkill",
    "ToolActivity",
    "BrowserActivity",
    "ProgressInfo",
    "CostInfo",
    "envelope",
    "message",
    "handoff",
    "review",
    "artifact",
    "activity",
    "capabilities",
    "ACPClient",
    "parse_sse_line",
    "stream_events",
    "connect_sse",
    "ComputerUseClient",
    "ComputerUseClientConfig",
    "ComputerUseActiveModelResponse",
    "ComputerUsePolicyResponse",
    "ComputerUseSessionListRecord",
    "ComputerUseSessionRecord",
    "ComputerUseSLOSummaryResponse",
    "ComputerUseStreamEvent",
    "NavigateComputerUseSessionResponse",
    "StartComputerUseSessionInput",
    "StartComputerUseSessionResponse",
    "StreamComputerUseSessionOptions",
    "cancel_computer_use_session",
    "create_computer_use_client",
    "get_computer_use_active_model",
    "get_computer_use_policy",
    "get_computer_use_session",
    "get_computer_use_slo_summary",
    "list_computer_use_sessions",
    "navigate_computer_use_session",
    "start_computer_use_session",
    "stream_computer_use_session",
    "TeamChat",
    "Theatre",
]
