"""Maia SDK - the collaboration and observability layer for AI agents.

One import, everything you need.

Quick start:

    from maia_sdk import Brain, ACPClient, Theatre, TeamChat, create_computer_use_client, message
"""

__version__ = "0.1.0"

from maia_brain import (
    AgentDefinition,
    AgentRole,
    Brain,
    BrainConfig,
    BrainResult,
    BrainStep,
    LLMConfig,
    LLMResult,
    MemoryEntry,
    MemoryStore,
    ResearchConfig,
    SearchResult,
    brave_search,
    call_llm,
    call_llm_json,
    filter_results,
    get_all_roles,
    get_role,
    infer_role,
)
from maia_acp import (
    ACPEvent,
    ACPMessage,
    ACPHandoff,
    ACPReview,
    ACPArtifact,
    ACPActivity,
    ACPCapabilities,
    HandoffTask,
    ReviewIssue,
    AgentPersonality,
    AgentSkill,
    ToolActivity,
    BrowserActivity,
    ProgressInfo,
    CostInfo,
    envelope,
    message,
    handoff,
    review,
    artifact,
    activity,
    capabilities,
    ACPClient,
    parse_sse_line,
    stream_events,
    connect_sse,
)
from maia_computer_use import (
    ComputerUseClient,
    ComputerUseClientConfig,
    ComputerUseActiveModelResponse,
    ComputerUsePolicyResponse,
    ComputerUseSessionListRecord,
    ComputerUseSessionRecord,
    ComputerUseSLOSummaryResponse,
    ComputerUseStreamEvent,
    NavigateComputerUseSessionResponse,
    StartComputerUseSessionInput,
    StartComputerUseSessionResponse,
    StreamComputerUseSessionOptions,
    cancel_computer_use_session,
    create_computer_use_client,
    get_computer_use_active_model,
    get_computer_use_policy,
    get_computer_use_session,
    get_computer_use_slo_summary,
    list_computer_use_sessions,
    navigate_computer_use_session,
    start_computer_use_session,
    stream_computer_use_session,
)
from maia_connectors import (
    BaseConnector,
    ConnectorDefinition,
    ConnectorTool,
    get_all_connectors,
    get_connector,
    get_connector_ids,
)
from maia_teamchat import TeamChat
from maia_theatre import Theatre

__all__ = [
    "Brain",
    "BrainConfig",
    "BrainResult",
    "BrainStep",
    "LLMConfig",
    "LLMResult",
    "ResearchConfig",
    "AgentDefinition",
    "AgentRole",
    "MemoryStore",
    "MemoryEntry",
    "SearchResult",
    "get_role",
    "get_all_roles",
    "infer_role",
    "call_llm",
    "call_llm_json",
    "brave_search",
    "filter_results",
    "ACPEvent",
    "ACPMessage",
    "ACPHandoff",
    "ACPReview",
    "ACPArtifact",
    "ACPActivity",
    "ACPCapabilities",
    "HandoffTask",
    "ReviewIssue",
    "AgentPersonality",
    "AgentSkill",
    "ToolActivity",
    "BrowserActivity",
    "ProgressInfo",
    "CostInfo",
    "envelope",
    "message",
    "handoff",
    "review",
    "artifact",
    "activity",
    "capabilities",
    "ACPClient",
    "parse_sse_line",
    "stream_events",
    "connect_sse",
    "BaseConnector",
    "ConnectorDefinition",
    "ConnectorTool",
    "get_connector",
    "get_all_connectors",
    "get_connector_ids",
    "ComputerUseClient",
    "ComputerUseClientConfig",
    "ComputerUseActiveModelResponse",
    "ComputerUsePolicyResponse",
    "ComputerUseSessionListRecord",
    "ComputerUseSessionRecord",
    "ComputerUseSLOSummaryResponse",
    "ComputerUseStreamEvent",
    "NavigateComputerUseSessionResponse",
    "StartComputerUseSessionInput",
    "StartComputerUseSessionResponse",
    "StreamComputerUseSessionOptions",
    "cancel_computer_use_session",
    "create_computer_use_client",
    "get_computer_use_active_model",
    "get_computer_use_policy",
    "get_computer_use_session",
    "get_computer_use_slo_summary",
    "list_computer_use_sessions",
    "navigate_computer_use_session",
    "start_computer_use_session",
    "stream_computer_use_session",
    "TeamChat",
    "Theatre",
]
