import type { ActivityEventLike, PreviewTab } from "./types";
import { eventMetadataString, tabForEventType } from "./activityMeta";
import { readNumberField, readStringField } from "./valueReaders";

const SURFACE_TO_TAB: Record<string, PreviewTab> = { browser: "browser", website: "browser", web: "browser", preview: "browser", maps: "browser", document: "document", google_docs: "document", google_sheets: "document", docs: "document", sheets: "document", email: "email", gmail: "email", api: "system", system: "system", workspace: "system" };
const UI_TARGET_TO_TAB: Record<string, PreviewTab> = { browser: "browser", document: "document", email: "email", system: "system", api: "system" };
const ROLE_LABELS: Record<string, string> = { conductor: "Conductor", planner: "Planner", research: "Research", browser: "Browser", writer: "Writer", verifier: "Verifier", safety: "Safety", document_reader: "Document", analyst: "Analyst", chart_builder: "Analyst", workspace_editor: "Writer", goal_page_discovery: "Browser", contact_form: "Browser", system: "System" };
const ROLE_COLORS: Record<string, string> = { conductor: "#7c3aed", planner: "#7c3aed", research: "#8b5cf6", browser: "#7c3aed", writer: "#7c2d12", verifier: "#15803d", safety: "#dc2626", document_reader: "#475569", analyst: "#7c3aed", chart_builder: "#7c3aed", workspace_editor: "#9333ea", goal_page_discovery: "#6d28d9", contact_form: "#6d28d9", system: "#6b7280" };
const ACTIONS = new Set(["navigate", "hover", "click", "type", "scroll", "zoom_in", "zoom_out", "zoom_reset", "zoom_to_region", "extract", "verify", "other"]);

function normalizeToken(value: string): string { return String(value || "").trim().toLowerCase().replace(/\s+/g, "_"); }
function toTitleFromSnake(value: string): string { return value.split("_").filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); }
function tabForSceneSurface(surface: string): PreviewTab | null { const normalized = normalizeToken(surface); return normalized ? SURFACE_TO_TAB[normalized] || null : null; }
function tabForUiTarget(target: string): PreviewTab | null { const normalized = normalizeToken(target); return normalized ? UI_TARGET_TO_TAB[normalized] || null : null; }
function isGoogleWorkspaceUrl(candidate: unknown): boolean { const value = readStringField(candidate).toLowerCase(); return Boolean(value && (value.includes("docs.google.com/document/") || value.includes("docs.google.com/spreadsheets/"))); }
function hasWorkspaceUrlSignal(event: ActivityEventLike): boolean { const candidates = [event.data?.["document_url"], event.metadata?.["document_url"], event.data?.["spreadsheet_url"], event.metadata?.["spreadsheet_url"], event.data?.["source_url"], event.metadata?.["source_url"], event.data?.["url"], event.metadata?.["url"], event.data?.["target_url"], event.metadata?.["target_url"]]; return candidates.some((candidate) => isGoogleWorkspaceUrl(candidate)); }
function isWorkspaceLoggingStep(event: ActivityEventLike, toolId: string): boolean { const markerRaw = event.data?.["__workspace_logging_step"] ?? event.metadata?.["__workspace_logging_step"]; const marker = typeof markerRaw === "boolean" ? markerRaw : ["true", "1", "yes"].includes(String(markerRaw ?? "").trim().toLowerCase()); return marker || toolId === "workspace.sheets.track_step"; }
function isShadowEvent(event: ActivityEventLike | null): boolean { if (!event) return false; const raw = event.data?.["shadow"] ?? event.metadata?.["shadow"]; if (typeof raw === "boolean") return raw; const normalized = String(raw ?? "").trim().toLowerCase(); return normalized === "true" || normalized === "1" || normalized === "yes"; }
function sceneSurfaceFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; const explicitSurface = eventMetadataString(event, "scene_surface") || readStringField(event.data?.["scene_surface"]) || ""; if (explicitSurface) return explicitSurface; const sceneFamily = eventMetadataString(event, "scene_family") || readStringField(event.data?.["scene_family"]) || ""; const family = normalizeToken(sceneFamily); if (family === "email") return "email"; if (family === "sheet") return "google_sheets"; if (family === "document") return "google_docs"; if (family === "browser") return "website"; if (family === "api" || family === "chat" || family === "crm" || family === "support" || family === "commerce") return "api"; return ""; }
function eventTab(event: ActivityEventLike | null): PreviewTab { if (!event || isShadowEvent(event)) return "system"; const normalizedType = readStringField(event.event_type).trim().toLowerCase(); const toolId = eventMetadataString(event, "tool_id") || readStringField(event.data?.["tool_id"]); const uiTarget = readStringField(event.data?.["ui_target"]) || readStringField(event.metadata?.["ui_target"]); const uiTargetTab = tabForUiTarget(uiTarget); if (uiTargetTab) return uiTargetTab; const interactionSurface = sceneSurfaceFromEvent(event); const surfaceTab = tabForSceneSurface(interactionSurface); if (surfaceTab === "document") { const explicitDocumentEvent = normalizedType.startsWith("document_") || normalizedType.startsWith("pdf_") || normalizedType.startsWith("doc_") || normalizedType.startsWith("docs.") || normalizedType.startsWith("sheet_") || normalizedType.startsWith("sheets.") || normalizedType === "drive.go_to_doc" || normalizedType === "drive.go_to_sheet"; if (!explicitDocumentEvent && !hasWorkspaceUrlSignal(event) && isWorkspaceLoggingStep(event, toolId)) return "system"; } if (surfaceTab) return surfaceTab; const byType = tabForEventType(event.event_type || ""); if (byType !== "system") return byType; if (toolId.startsWith("browser.") || toolId.startsWith("marketing.web_research")) return "browser"; return "system"; }
function isApiRuntimeEvent(event: ActivityEventLike | null): boolean { if (!event) return false; const sceneSurface = sceneSurfaceFromEvent(event).toLowerCase(); if (sceneSurface === "api") return true; const eventFamily = readStringField(event.data?.["event_family"]) || readStringField(event.metadata?.["event_family"]) || ""; if (eventFamily.trim().toLowerCase() === "api") return true; const eventType = readStringField(event.event_type).trim().toLowerCase(); return eventType.startsWith("api_") || eventType.startsWith("api."); }
function cursorFromEvent(event: ActivityEventLike | null): { x: number; y: number } | null { if (!event) return null; const x = readNumberField(event.data?.["cursor_x"]) ?? readNumberField(event.metadata?.["cursor_x"]); const y = readNumberField(event.data?.["cursor_y"]) ?? readNumberField(event.metadata?.["cursor_y"]); if (x === null || y === null) return null; return { x: Math.max(2, Math.min(98, x)), y: Math.max(2, Math.min(98, y)) }; }
function roleKeyFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; const candidate = readStringField(event.data?.["owner_role"]) || readStringField(event.metadata?.["owner_role"]) || readStringField(event.data?.["__owner_role"]) || readStringField(event.metadata?.["__owner_role"]) || readStringField(event.data?.["role"]) || readStringField(event.metadata?.["role"]) || readStringField(event.data?.["to_role"]) || readStringField(event.metadata?.["to_role"]) || readStringField(event.data?.["agent_role"]) || readStringField(event.metadata?.["agent_role"]); return normalizeToken(candidate); }
function roleLabelFromKey(roleKey: string): string { const normalized = normalizeToken(roleKey); return normalized ? ROLE_LABELS[normalized] || toTitleFromSnake(normalized) : ""; }
function roleColorFromKey(roleKey: string): string { const normalized = normalizeToken(roleKey); return normalized ? ROLE_COLORS[normalized] || ROLE_COLORS.system : ROLE_COLORS.system; }
function agentLabelFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; const explicitLabel = readStringField(event.data?.["agent_label"]) || readStringField(event.metadata?.["agent_label"]); return explicitLabel || roleLabelFromKey(roleKeyFromEvent(event)); }
function agentColorFromEvent(event: ActivityEventLike | null): string { if (!event) return ROLE_COLORS.system; const explicitColor = readStringField(event.data?.["agent_color"]) || readStringField(event.metadata?.["agent_color"]); return explicitColor || roleColorFromKey(roleKeyFromEvent(event)); }
function agentEventTypeFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; return (readStringField(event.data?.["agent_event_type"]) || readStringField(event.metadata?.["agent_event_type"]) || readStringField(event.event_type)).trim().toLowerCase(); }
function interactionActionFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; const normalized = normalizeToken(readStringField(event.data?.["action"]) || readStringField(event.metadata?.["action"]) || ""); return ACTIONS.has(normalized) ? normalized : ""; }
function interactionActionPhaseFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; return normalizeToken(readStringField(event.data?.["action_phase"]) || readStringField(event.metadata?.["action_phase"])); }
function interactionActionStatusFromEvent(event: ActivityEventLike | null): string { if (!event) return ""; return normalizeToken(readStringField(event.data?.["action_status"]) || readStringField(event.metadata?.["action_status"]) || readStringField(event.status)); }
function surfaceLabelForSceneKey(sceneSurfaceKey: string): string { const key = normalizeToken(sceneSurfaceKey); if (key === "website") return "Website"; if (key === "google_sheets") return "Google Sheets"; if (key === "google_docs") return "Google Docs"; if (key === "document") return "Document"; if (key === "email") return "Email"; if (key === "api") return "API"; if (key === "workspace") return "Workspace"; return "System"; }
function cursorLabelFromSemantics(args: { action: string; actionStatus: string; actionPhase: string; sceneSurfaceLabel: string; roleLabel: string; agentEventType?: string; }): string { const action = normalizeToken(args.action); const status = normalizeToken(args.actionStatus); const phase = normalizeToken(args.actionPhase); const subject = String(args.roleLabel || "").trim() || "Agent"; const surfaceLabel = String(args.sceneSurfaceLabel || "workspace").trim().toLowerCase(); const agentEventType = String(args.agentEventType || "").trim().toLowerCase(); if (agentEventType.includes("waiting")) return `${subject} awaiting confirmation`; if (agentEventType.includes("blocked")) return `${subject} blocked`; if (agentEventType.includes("handoff")) return `${subject} handing off`; if (agentEventType.includes("resume")) return `${subject} resumed`; if (status === "failed") return `${subject} retrying`; if (action === "navigate") return `${subject} opening ${surfaceLabel}`; if (action === "click") return `${subject} selecting target`; if (action === "type") return `${subject} typing`; if (action === "scroll") return `${subject} scanning`; if (action === "zoom_in") return `${subject} zooming in`; if (action === "zoom_out") return `${subject} zooming out`; if (action === "zoom_reset") return `${subject} resetting zoom`; if (action === "zoom_to_region") return `${subject} inspecting detail`; if (action === "extract") return `${subject} gathering evidence`; if (action === "verify") return `${subject} verifying`; if (phase === "start" || phase === "active") return `${subject} working`; return `${subject} active`; }
function roleNarrativeFromSemantics(args: { roleLabel: string; action: string; sceneSurfaceLabel: string; fallback: string; agentEventType?: string; }): string { const roleLabel = String(args.roleLabel || "").trim() || "Agent"; const action = normalizeToken(args.action); const surface = String(args.sceneSurfaceLabel || "workspace").trim().toLowerCase(); const agentEventType = String(args.agentEventType || "").trim().toLowerCase(); if (agentEventType.includes("handoff")) return `${roleLabel} is handing control to the next specialist.`; if (agentEventType.includes("waiting")) return `${roleLabel} is waiting for human verification.`; if (agentEventType.includes("blocked")) return `${roleLabel} is blocked by a policy or verification rule.`; if (agentEventType.includes("resume")) return `${roleLabel} resumed execution.`; if (action === "navigate") return `${roleLabel} is opening ${surface}.`; if (action === "click") return `${roleLabel} is selecting a target in ${surface}.`; if (action === "type") return `${roleLabel} is composing output in ${surface}.`; if (action === "scroll") return `${roleLabel} is scanning ${surface}.`; if (action === "zoom_in") return `${roleLabel} is zooming in on ${surface}.`; if (action === "zoom_out") return `${roleLabel} is zooming out in ${surface}.`; if (action === "zoom_reset") return `${roleLabel} is resetting zoom in ${surface}.`; if (action === "zoom_to_region") return `${roleLabel} is zooming to a focus region in ${surface}.`; if (action === "extract") return `${roleLabel} is gathering evidence from ${surface}.`; if (action === "verify") return `${roleLabel} is verifying completion in ${surface}.`; return `${roleLabel} is ${String(args.fallback || "working").trim().toLowerCase()}.`; }

export { agentColorFromEvent, agentEventTypeFromEvent, agentLabelFromEvent, cursorFromEvent, cursorLabelFromSemantics, eventTab, interactionActionFromEvent, interactionActionPhaseFromEvent, interactionActionStatusFromEvent, isApiRuntimeEvent, roleColorFromKey, roleKeyFromEvent, roleLabelFromKey, roleNarrativeFromSemantics, sceneSurfaceFromEvent, surfaceLabelForSceneKey, tabForSceneSurface };
